### ISSUE TITLE
Update terms "measurement method" and "measurement type"

### ISSUE THREAD

**Issue by cboelling** [MfN-Berlin/AnimalAudiogramDatabase#3]
In the basic filter in the [browse-interface](https://animalaudiograms.museumfuernaturkunde.berlin/audiogrambase) the term ***"measurement method"*** is used to select either of the two main experimental approaches (behavioral and electrophysiological) while the term ***"measurement type"*** is used to select the type of measurement, i.e. auditory thresholds vs. critical ratios etc.

These terms are too similar. At least one of them should be updated to a different term (here and elsewhere in the interface) to make these categories understandable at a glance.

**Comment by alvarosaurus** [comment]
what terms do you suggest?

**Comment by cboelling** [comment]
> 
> 
> what terms do you suggest?

I propose the change the terms on the indicated page as follows:

measurement method --> general methodology
(as currently only the two main categories *behavioral* and *electrophysiological* are offered for selection)

measurement type --> measurement objective
(indicate *what* was measured)

**Comment by alvarosaurus** [comment]
OK we'll have to check the proposed terms with domain experts.

**Comment by cboelling** [comment]
> 
> 
> OK we'll have to check the proposed terms with domain experts.

This was discussed with Michael, we can go ahead and implement these changes.

**Comment by alvarosaurus** [comment]
Closing as patch merged into main
